(() => {
'use strict';
const app=document.getElementById('app'), questions=window.QUIZ_QUESTIONS, config=window.QUIZ_CONFIG;
const categories=[...new Set(questions.map(q=>q.category))];
let index=-1, answers=[], locked=false, attemptId;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function focusTitle(){app.querySelector('h1,h2')?.focus();window.scrollTo({top:0,behavior:'instant'});}
function startScreen(){index=-1;answers=[];locked=false;app.innerHTML='<section class="start-screen"><div class="cover"><div class="cover-art"><img src="daecheong-judge.png" alt="법봉과 법률책을 든 대청 캐릭터" width="320" height="320"></div><h1 tabindex="-1"><span class="cohort">청소년 로스쿨 <em>11기</em></span><span class="title-main">법률을 맞춰봐</span></h1><button class="primary" id="start">시작하기</button></div></section>';document.getElementById('start').onclick=start;}
function start(){attemptId=globalThis.crypto?.randomUUID?.();index=0;answers=[];locked=false;renderQuestion();}
function renderQuestion(){locked=answers[index]!==undefined;const q=questions[index];app.innerHTML=`<div class="quiz-heading"><strong>법률을 맞춰봐</strong><span id="live-score" class="score-pill">점수: ${questions.reduce((n,q,i)=>n+(answers[i]===q.answer?10:0),0)}</span></div><section class="panel quiz"><div class="progress-meta"><span>${index+1} / 10</span></div><progress max="10" value="${index+1}" aria-label="완료한 문제"></progress><span class="category">${escape(q.category)}</span><h2 tabindex="-1">${escape(q.question)}</h2><div class="options" aria-label="정답 선택">${q.options.map((o,i)=>`<button class="option" data-answer="${i}"><span>${escape(o)}</span></button>`).join('')}</div><div id="feedback" class="feedback" aria-live="polite" hidden></div><div class="navigation"><button class="secondary" id="back">되돌아가기</button><button class="primary" id="next" disabled>${index===9?'내 결과 보기':'다음 문제'}</button></div><p id="choose-hint" hidden></p></section>`;app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));document.getElementById('next').onclick=next;document.getElementById('back').onclick=()=>{if(index===0){startScreen();}else{index--;renderQuestion();}};if(locked)showAnswer(answers[index]);focusTitle();}
function answer(choice){if(index<0||index>=10||locked||!Number.isInteger(choice)||choice<0||choice>3)return false;locked=true;answers[index]=choice;showAnswer(choice);return true;}
function showAnswer(choice){document.getElementById('live-score').textContent='점수: '+questions.reduce((n,q,i)=>n+(answers[i]===q.answer?10:0),0);const q=questions[index];app.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.answer){b.classList.add('correct');b.insertAdjacentHTML('beforeend','<span class="answer-status">✓ 정답</span>');}else if(i===choice){b.classList.add('wrong');b.insertAdjacentHTML('beforeend','<span class="answer-status">내 선택</span>');}});const feedback=document.getElementById('feedback');feedback.hidden=false;feedback.className='feedback '+(choice===q.answer?'success':'review-feedback');feedback.innerHTML=`<h3>${choice===q.answer?'정답입니다.':'정답을 확인해 보세요.'}</h3><p>${escape(q.explanation)}</p><a href="${escape(q.source.url)}" target="_blank" rel="noopener noreferrer">근거 보기 · ${escape(q.source.law)} 제${q.source.article}조 ↗</a>`;document.getElementById('next').disabled=false;document.getElementById('choose-hint').hidden=true;document.getElementById('next').focus({preventScroll:true});return true;}
function next(){if(!locked||index>=10)return false;index++;locked=false;if(index===10)renderResult();else renderQuestion();return true;}
function validApplicationUrl(){try{const u=new URL(config.applicationUrl);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function renderResult(){const correct=questions.reduce((n,q,i)=>n+(answers[i]===q.answer),0),url=validApplicationUrl();app.innerHTML=`<section class="panel result"><h2 tabindex="-1">테스트 결과</h2><div class="score">${correct*10}<small> / 100점</small></div><p>${correct===10?'모든 문제를 맞혔어요! 멋진 출발이에요.':`10문항 중 ${correct}문항 정답! 오늘 알게 된 법을 기억해 보세요.`}</p><div class="breakdown">${categories.map(c=>{const n=questions.reduce((sum,q,i)=>sum+(q.category===c&&answers[i]===q.answer),0);return `<div class="row"><span>${escape(c)}</span><strong>${n} / 2 정답</strong><progress max="2" value="${n}" aria-label="${escape(c)} ${n}문항 정답"></progress></div>`;}).join('')}</div><section class="ranking" id="ranking" aria-live="polite"></section><div class="invite"><p>청소년 로스쿨 11기에서<br>더 많은 법률 문제에 도전해보세요!</p>${url?`<a class="primary" href="${escape(url)}" target="_blank" rel="noopener noreferrer">청소년 로스쿨 11기 신청하기</a>`:'<button class="primary" disabled>청소년 로스쿨 11기 신청하기</button><div class="note">신청 링크 준비 중이에요.</div>'}</div><button class="secondary" id="review">이전 문제로</button><button class="secondary" id="restart">다시 도전하기</button></section>`;document.getElementById('review').onclick=()=>{index=9;renderQuestion();};document.getElementById('restart').onclick=start;focusTitle();const area=document.getElementById('ranking');area.innerHTML='<button class="secondary" id="compare">참여 기록과 비교하기</button><p class="note">참여자 순위는 준비 중이며, 현재 응답은 서버에 저장하지 않습니다.</p>';document.getElementById('compare').onclick=()=>window.loadQuizRanking?.([...answers],attemptId);}
startScreen();
// 지원 브라우저에서 화면과 같은 동작을 제공하며, 문제 생성 기능은 없습니다.
const context=document.modelContext;
if(context?.registerTool){const controller=new AbortController();window.addEventListener('pagehide',()=>controller.abort(),{once:true});const tool={name:'start_law_quiz',description:'고정된 10문항 퀴즈를 처음부터 시작합니다. 기존 응답을 초기화합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('빈 객체만 허용됩니다.');start();return {questionNumber:1,total:10};}};try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}
})();








